@isTest
public class AsyncSapComDocumentTest {
@IsTest
    public static void testSub(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
      //  AsyncSapComDocumentSapRfcFunctions_DUP.x_xGEL_xSFB2B_RETURNS_CREATE_Response_elementFuture();
        
       // Test.startTest();
       // AsyncSapComDocumentSapRfcFunctions_DUP.x_xGEL_xSFB2B_RETURNS_CREATE_Response_elementFuture();
       // Test.stopTest();
    }
}