public class CaseConstants {
    public static Final String EMAIL = 'Email';
    Public static final string QUEUE = 'Queue';
    public static final string EMAIL_REG_EXP = '^[A-Za-z0-9._%+-/!#$%&*=?^_`{|}~]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}$';
    public static final string NE_RECORD_TYPE = 'North America';
    public static final string WEB = 'Web';
    public static final string SHIPPING_SUBJECT = 'SHIPPING DISCREPANCY';
    public static final string BILLING_ADJUSTMENT = 'Billing Adjustment';
    public static final string STOCKBALANCING_CLAIM= 'Stockbalancing claim';
    public static final string ELIGHT_RETURNS = 'Initiate a Return';
     public static final string ELIGHT_ORIGIN = 'eLight - Return Request';
    public static final string END_OF_Products = 'End of Products'; 
}