@isTest
public with sharing class sapComDocSapRfcFunctionsRMATest {
    @isTest
    public static void test() {
        sapComDocSapRfcFunctionsRMA.x_xGEL_xSFB2B_PRINT_RET_ORDER_Response_element t1 = new sapComDocSapRfcFunctionsRMA.x_xGEL_xSFB2B_PRINT_RET_ORDER_Response_element();
        sapComDocSapRfcFunctionsRMA.x_xGEL_xSDOMPRINT_ORDERCONF_HI t2 = new sapComDocSapRfcFunctionsRMA.x_xGEL_xSDOMPRINT_ORDERCONF_HI();
        sapComDocSapRfcFunctionsRMA.BAPIRET2 t3 = new sapComDocSapRfcFunctionsRMA.BAPIRET2();
        sapComDocSapRfcFunctionsRMA.x_xGEL_xSFB2B_PRINT_RET_ORDER_element t4 = new sapComDocSapRfcFunctionsRMA.x_xGEL_xSFB2B_PRINT_RET_ORDER_element();
    }
}