@isTest
public with sharing class sapComDocumentSapRfcFunctionsTest {
    @isTest
    public static void test(){
        sapComDocumentSapRfcFunctions.ET_MATERIALS_OUT_element t1 = new sapComDocumentSapRfcFunctions.ET_MATERIALS_OUT_element();
        sapComDocumentSapRfcFunctions.ET_SCHEDULELINE_DATA_element t2 = new sapComDocumentSapRfcFunctions.ET_SCHEDULELINE_DATA_element();
        sapComDocumentSapRfcFunctions.x_xGEL_xHY_AGREEMENT_PRICE_CALL_Response_element t3 = new sapComDocumentSapRfcFunctions.x_xGEL_xHY_AGREEMENT_PRICE_CALL_Response_element();
        sapComDocumentSapRfcFunctions.x_xGEL_xHYBRIS_SCH_LINE t4 = new sapComDocumentSapRfcFunctions.x_xGEL_xHYBRIS_SCH_LINE();
        sapComDocumentSapRfcFunctions.x_xGEL_xHY_AGR_PRICE_MATERIALS_OU t5 = new sapComDocumentSapRfcFunctions.x_xGEL_xHY_AGR_PRICE_MATERIALS_OU();
        sapComDocumentSapRfcFunctions.x_xGEL_xHY_AGR_PRICE_MATERIALS t6 = new sapComDocumentSapRfcFunctions.x_xGEL_xHY_AGR_PRICE_MATERIALS();
        sapComDocumentSapRfcFunctions.x_xGEL_xHY_AGREEMENT_PRICE_CALL_element t7 = new sapComDocumentSapRfcFunctions.x_xGEL_xHY_AGREEMENT_PRICE_CALL_element();
        sapComDocumentSapRfcFunctions.IT_MATERIALS_element t8 = new sapComDocumentSapRfcFunctions.IT_MATERIALS_element();
        sapComDocumentSapRfcFunctions.x_xGEL_xHY_ITEM_OUT t9 = new sapComDocumentSapRfcFunctions.x_xGEL_xHY_ITEM_OUT();
        sapComDocumentSapRfcFunctions.IT_ITEMIN_element t10 = new sapComDocumentSapRfcFunctions.IT_ITEMIN_element();
        sapComDocumentSapRfcFunctions.IT_HEAD_COMMENTS_element t11 = new sapComDocumentSapRfcFunctions.IT_HEAD_COMMENTS_element();
        sapComDocumentSapRfcFunctions.x_xGEL_xHY_ORDER_TEXT t12 = new sapComDocumentSapRfcFunctions.x_xGEL_xHY_ORDER_TEXT();
        sapComDocumentSapRfcFunctions.ET_ITEMOUT_element t13 = new sapComDocumentSapRfcFunctions.ET_ITEMOUT_element();
        sapComDocumentSapRfcFunctions.x_xGEL_xSFB2B_ORDER_CREATE_Response_element t14 = new sapComDocumentSapRfcFunctions.x_xGEL_xSFB2B_ORDER_CREATE_Response_element();
        sapComDocumentSapRfcFunctions.x_xGEL_xSFB2B_ORDER_CREATE_element t15 = new sapComDocumentSapRfcFunctions.x_xGEL_xSFB2B_ORDER_CREATE_element();
        sapComDocumentSapRfcFunctions.x_xGEL_xHY_ORDER_ITEM t16 = new sapComDocumentSapRfcFunctions.x_xGEL_xHY_ORDER_ITEM();
        sapComDocumentSapRfcFunctions.IT_HEAD_SHIP_INSTRU_element t17 = new sapComDocumentSapRfcFunctions.IT_HEAD_SHIP_INSTRU_element();
        sapComDocumentSapRfcFunctions.IT_ITEM_COMMENTS_element t18 = new sapComDocumentSapRfcFunctions.IT_ITEM_COMMENTS_element();
    }
}