public with sharing class StaticVariables {

  public static Boolean sendEmail= true;
  public static Boolean deleteOpptyProduct = false;
  public static Boolean runningAgreementItemBatch = false;
  public static Boolean runningAgreementBatch = false;
  public static Boolean runningQuoteItemBatch = false;
  public static Boolean runningQuoteBatch = false;  
  public static boolean RequestAggsRunning = false;
  public static boolean ReleaseAggsRunning = false;
  public static boolean ProjectAggsRunning = false;
  public static boolean SprintAggsRunning = false;
  public static boolean TeamMemberAggsRunning = false;
  public static Boolean insertTeamMemberFromOpp = true;
  public static Boolean doNotSetActualHours = true ;
  public static Boolean aggsRunningFromRelComp = false ;
  public static Boolean aggsRunningFromDelTsk = false ;
  public static Boolean aggsRunningFromRequest = false ; 
  public static Boolean settingReleaseFromRequest = false;
  public static Boolean unSyncQuoteFlag = TRUE;
  
}